heightmaps:
  ground:
    default: 0
sources:
  mnt:
    modelType: mnt
    provider:
      type: wmsFloat
      url: https://data.geopf.fr/wms-r/wms
      layer: RGEALTI-MNT_PYR-ZIP_FXX_LAMB93_WMS
    processor:
      type: floatMatrix
  bati:
    modelType: building
    provider:
      type: wfs
      url: https://data.geopf.fr/wfs/wfs
      features: BDTOPO_V3:batiment
    processor:
      type: geoToolsVector
    postProcessors:
      - type: copy
        metadata: hauteur
        to: height
      - type: parse
        metadata: height
        as: decimal
        ifMissing: ignore
        ifNotParsable: removeMetadata
      - type: default
        metadata: height
        value: 5
        as: integer
renderers:
  altitude:
    after:
      - source:mnt
    type: heightmap
    models:
      type: mnt
    heightmap: ground
  ground:
    after:
      - renderer:altitude
    type: ground
    heightmap: ground
    place:
      type: stack
      direction: downwards
      layers:
        - material: default:dirt_with_grass
        - material: default:dirt
          height: 3
        - material: default:stone
          height: 10
  building-leveling:
    after:
      - source:bati
      - renderer:ground
    type: leveling
    models:
      type: building
    heightmap: ground
    filling: default:cobble
  building:
    after:
      - renderer:building-leveling
    type: building
    models:
      type: building
      filter:
        not:
          or:
            - metadata: height
              lowerThan: 0
            - metadata: height
              equals: 0
    heightmap: ground
    roof: default:cobble
    wall: default:stone
    window: default:glass
verticalScale: 1.0
horizontalScale: 1.0
area:
  center:
    latitude: 48.845
    longitude: 2.425
  angle: 0
  extentX: 1000
  extentY: 1000
crs: EPSG:2154
format: minetest
