heightmaps:
  ground:
    default: 0
sources:
  mnt:
    modelType: mnt
    provider:
      type: wmsFloat
      url: https://data.geopf.fr/wms-r/wms
      layer: RGEALTI-MNT_PYR-ZIP_FXX_LAMB93_WMS
    processor:
      type: floatMatrix
  bati:
    modelType: building
    provider:
      type: wfs
      url: https://data.geopf.fr/wfs/wfs
      features: BDTOPO_V3:batiment
    processor:
      type: geoToolsVector
    postProcessors:
      - type: copy
        metadata: hauteur
        to: height
  road:
    modelType: road
    provider:
      type: wfs
      url: https://data.geopf.fr/wfs/wfs
      features: BDTOPO_V3:troncon_de_route
    processor:
      type: geoToolsVector
  railroad:
    modelType: railroad
    provider:
      type: wfs
      url: https://data.geopf.fr/wfs/wfs
      features: BDTOPO_V3:troncon_de_voie_ferree
    processor:
      type: geoToolsVector
renderers:
  altitude:
    after:
      - source:mnt
    type: heightmap
    modelType: mnt
    heightmap: ground
  ground:
    after:
      - renderer:altitude
    type: ground
    heightmap: ground
    place:
      type: stack
      direction: downwards
      layers:
        - material: default:dirt_with_grass
        - material: default:dirt
          height: 3
        - material: default:stone
          height: 30
  building:
    after:
      - renderer:altitude
      - source:bati
    type: vector
    modelType: building
    heightmap: ground
    inside: default:cobble
    edge: default:stonebrick
  bridges:
    after:
      - source:road
      - renderer:ground
    type: linear
    modelType: road
    renderOnlyWhenAbove: ground
    at: 0..4
    place:
      type: stack
      offset: -1
      layers:
        - material: default:stonebrick
          height: 2
        - material:
            node: stairs:slab_stonebrick
            param2: 0
        - material: air
          height: 1
  roads:
    after:
      - source:road
      - renderer:bridges
    type: linear
    modelType: road
    at: 0..3
    place:
      type: stack
      layers:
        - material: default:obsidian
        - material: air
          height: 4
  tunnel:
    after:
      - source:railroad
      - renderer:ground
    type: linear
    modelType: railroad
    at: 0..3
    place:
      type: stack
      offset: 1
      layers:
        - material: air
          height: 4
  ballast:
    after:
      - source:railroad
      - renderer:tunnel
    type: linear
    modelType: railroad
    at: 0..3
    place: default:gravel
  rails:
    after:
      - source:railroad
      - renderer:ballast
    type: linear
    modelType: railroad
    at: 2
    place:
      type: stack
      offset: 1
      layers:
        - material: carts:rail
verticalScale: 1.0
horizontalScale: 1.0
area:
  center:
# I love Saint Mandé
#    latitude: 48.84593
#    longitude: 2.42372
# Echangeur de Bagnolet
#    latitude: 48.866
#    longitude: 2.414
# Viaduc de Millau
#    latitude: 44.085636190025575
#    longitude: 3.0216182867051864
# St Lazarre - Place de l'Europe
#    latitude: 48.8790816561616
#    longitude: 2.323464685493046
# Rail Porn à Villeneuve
#    latitude: 48.75693562069861
#    longitude: 2.436901192048874
# Culs de sac à Boulouris
#    latitude: 43.42136382963531
#    longitude: 6.793996874139488
# Pont Martrou à Rochefort, avec un glitch à une extrémité
    latitude: 45.91722146731518
    longitude: -0.9670081885337489
  extendX: 1000
  extendY: 1000
crs: EPSG:2154
format: minetest
