name: checkstyle
run-name: ${{ github.actor }} is style-checking ${{ github.repository }}#${{ github.ref_name }}
on:
  push:
    paths:
      - src/**
      - pom.xml
      - checkstyle.xml
      - .github/workflows/checkstyle.yml

jobs:
  checkstyle:
    name: checkstyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run checkstyle
        uses: dbelyaev/action-checkstyle@v3.10.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: checkstyle.xml
          checkstyle_version: "13.5.0"
          level: error
          fail_level: error
          reporter: github-pr-annotations
          reviewdog_flags: -name checkstyle
