name: Main Docker pipeline
run-name: "[docker] ${{ github.actor }} from ${{ github.ref }} triggered by ${{ github.event_name }} event"

on:
  push:
    paths:
    - src/**
    - pom.xml
    - Dockerfile
    - .m2-settings.xml
    - .github/workflows/docker*.yml
  pull_request:
  delete:
  create:


jobs:
  build-and-push:
    if: github.event_name == 'push'
    uses: ./.github/workflows/docker-build-push.yml
    with:
      registry: "ghcr.io"
      image_name: "${{ github.repository }}"
      branch_name: "${{ github.ref_name }}"

  build:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/docker-build.yml

  delete-branch-image:
    if: |
      github.event_name == 'delete' &&
      github.event.ref_type == 'branch'
    uses: ./.github/workflows/docker-delete-branch-image.yml
    with:
      branch_name: ${{ github.event.ref }}

  create-branch-image:
    if: |
      github.event_name == 'create' &&
      github.event.ref_type == 'branch'
    uses: ./.github/workflows/docker-build-push.yml
    with:
      registry: "ghcr.io"
      image_name: "${{ github.repository }}"
      branch_name: "${{ github.event.ref }}"
