name: String sanitization
run-name: "[docker-sanitize] ${{ github.actor }} from ${{ github.ref }} triggered by ${{ github.event_name }} event"

on:
  workflow_call:
    inputs:
      repository:
        description: "raw repository name"
        type: string
        default: "placeholder_repository"
      tag:
        description: "raw tag"
        type: string
        default: "placeholder_tag"
    outputs:
      repository:
        description: "Sanitized repository name"
        value: ${{ jobs.sanitization.outputs.sanitized_repository }}
      tag:
        description: "Sanitized tag name"
        value: ${{ jobs.sanitization.outputs.sanitized_tag }}

jobs:
  sanitization:
    name: Generate sanitized outputs
    runs-on: ubuntu-latest
    outputs:
      sanitized_repository: ${{ steps.sanitize_repo.outputs.SAFE_REPO_NAME }}
      sanitized_tag: ${{ steps.sanitize_tag.outputs.SAFE_TAG_NAME }}
    steps:
    - name: Sanitize repository name
      id: sanitize_repo
      env:
        RAW_REPO_NAME: ${{ inputs.repository }}
      run: echo "SAFE_REPO_NAME=$(echo ${RAW_REPO_NAME,,})" >> $GITHUB_OUTPUT
    - name: Sanitize tag name
      id: sanitize_tag
      env:
        RAW_BRANCH_NAME: ${{ inputs.tag }}
      # Docker tag name syntax specified by https://pkg.go.dev/github.com/distribution/reference is [\w][\w.-]{0,127}
      # Golang \w only matches [0-9A-Za-z_] limited to ASCII printable characters
      # Here we are using a regex to match the allowed characters and replacing all other characters with '_'
      run: echo "SAFE_TAG_NAME=$(TMP=${RAW_BRANCH_NAME,,}; echo "${TMP//[^a-zA-Z0-9_\.-]/_}")" >> $GITHUB_OUTPUT
    - name: Verify tag name
      env:
        CANDIDATE_TAG_NAME: ${{ steps.sanitize_tag.outputs.SAFE_TAG_NAME }}
        RAW_BRANCH_NAME: ${{ inputs.tag }}
      run: |
        if [[ ! ${CANDIDATE_TAG_NAME} =~ ^[a-zA-Z0-9_][a-zA-Z0-9_\.-]{0,127}$ ]]; then
          echo "Tag name '${CANDIDATE_TAG_NAME}' is invalid. It must obey '[\w][\w.-]{0,127}'. Please review branch '${RAW_BRANCH_NAME}' naming"
          exit 1
        fi
