name: Javadoc
run-name: ${{ github.actor }} is generating Javadoc for ${{ github.repository }}#${{ github.ref_name }}
on:
  push:
    # Main branch already builds and deploy Javadoc as part of the GitHub Pages site deployment (see github-pages.yml)
    branches-ignore:
      - main
    paths:
      - src/main/java/**
      - pom.xml
      - .github/workflows/javadoc.yml

jobs:
  javadoc:
    name: javadoc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java & Maven
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: temurin
          cache: maven
      - name: Generate Javadoc with Maven
        run: mvn --batch-mode --no-transfer-progress --update-snapshots javadoc:javadoc
      - name: Upload standard artifact
        uses: actions/upload-artifact@v4
        with:
          name: Javadoc
          path: target/site/apidocs
          if-no-files-found: error
