name: Unit-Tests
run-name: ${{ github.actor }} is testing ${{ github.repository }}#${{ github.ref_name }}
on:
  push:
    paths:
      - src/**
      - pom.xml
      - .github/workflows/unit-tests.yml

jobs:
  Unit-Tests:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java & Maven
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Test with Maven
        run: mvn --batch-mode --no-transfer-progress --update-snapshots test
