name: Unit-Tests
run-name: ${{ github.actor }} is testing ${{ github.repository }}#${{ github.ref_name }}
on:
  push:
    paths:
      - src/**
      - pom.xml
      - .github/workflows/unit-tests.yml

jobs:
  Unit-Tests:
    name: unit-tests
    runs-on: ubuntu-latest
    container:
      image: maven
    steps:
      - uses: actions/checkout@v4
      - run: mvn test
